"""Sample-image helper.

Per PLAN.md, test/dev code should call ``radquant.data.sample(n, ...)`` rather
than hardcoding paths. Images come from the ChestAgentBench ``figures`` bundle
downloaded by ``scripts/setup.py``.

If the preprocessing manifest exists (generated by
``python -m radquant.data.preprocess``), lookups are instant (no rglob).
"""

from __future__ import annotations

import random
from pathlib import Path
from typing import Optional

from radquant.config import DATA_DIR

CHESTAGENTBENCH_DIR = DATA_DIR / "chestagentbench"
MANIFEST_PATH = CHESTAGENTBENCH_DIR / "manifest.json"
_IMAGE_EXTS = {".png", ".jpg", ".jpeg"}


def load_manifest() -> Optional[dict]:
    """Load the preprocessed manifest, or None if not generated yet."""
    if not MANIFEST_PATH.exists():
        return None
    import json
    return json.loads(MANIFEST_PATH.read_text())


def _all_figures() -> list[Path]:
    """Return all valid image paths, preferring the manifest for speed."""
    # Fast path: use the preprocessed manifest if available
    manifest = load_manifest()
    if manifest and manifest.get("images"):
        paths = [Path(img["path"]) for img in manifest["images"]
                 if Path(img["path"]).exists()]
        if paths:
            return sorted(paths)

    # Slow fallback: rglob scan
    if not CHESTAGENTBENCH_DIR.exists():
        return []
    return sorted(
        p for p in CHESTAGENTBENCH_DIR.rglob("*")
        if p.suffix.lower() in _IMAGE_EXTS
        and "thumbnails" not in str(p)  # exclude generated thumbnails
    )


def sample(n: int = 1, pathology: str | None = None, modality: str = "cxr",
           seed: int | None = 0) -> list[Path]:
    """Return ``n`` sample image paths from the ChestAgentBench figures.

    Args:
        n: number of images to return.
        pathology: not yet supported (figures lack per-image pathology labels);
            passing it logs no error but currently does not filter. Phase 3+ may
            wire this through the benchmark metadata. Reserved for forward-compat.
        modality: reserved; only "cxr" is available in v1.
        seed: deterministic selection by default; pass ``None`` for random.

    Raises:
        FileNotFoundError: if the figures bundle has not been downloaded yet.
    """
    figures = _all_figures()
    if not figures:
        raise FileNotFoundError(
            f"No ChestAgentBench figures found under {CHESTAGENTBENCH_DIR}. "
            "Run `python scripts/setup.py` first."
        )
    if n >= len(figures):
        return figures
    if seed is None:
        return random.sample(figures, n)
    return random.Random(seed).sample(figures, n)
