"""Sample-image helper.

Per PLAN.md, test/dev code should call ``radquant.data.sample(n, ...)`` rather
than hardcoding paths. Images come from the ChestAgentBench ``figures`` bundle
downloaded by ``scripts/setup.py``.

If the preprocessing manifest exists (generated by
``python -m radquant.data.preprocess``), lookups are instant (no rglob).
"""

from __future__ import annotations

import random
from pathlib import Path
from typing import Optional

from radquant.config import DATA_DIR

CHESTAGENTBENCH_DIR = DATA_DIR / "chestagentbench"
MANIFEST_PATH = CHESTAGENTBENCH_DIR / "manifest.json"
DEMO_CXR_DIR = DATA_DIR / "demo_cxr"
_IMAGE_EXTS = {".png", ".jpg", ".jpeg"}


def demo_cxr(n: int | None = 8) -> list[Path]:
    """Return real *frontal chest X-rays* bundled for the demo worklist.

    Unlike :func:`sample` (which returns ChestAgentBench *figures* — CT/MRI/
    histology/annotated panels meant for the multiple-choice VQA eval, and which
    are out-of-distribution for the CXR classifier), these are actual chest
    radiographs (normal + pneumonia). Use this to seed the worklist so the
    classifier / Grad-CAM / triage operate on the modality they were built for.

    Returns a clinically mixed order (normals first, then pneumonia, then the
    bundled author examples) so a seeded worklist shows a meaningful spread.
    """
    if not DEMO_CXR_DIR.exists():
        return []
    imgs = [p for p in DEMO_CXR_DIR.rglob("*") if p.suffix.lower() in _IMAGE_EXTS]

    def rank(p: Path) -> tuple[int, str]:
        name = p.name.lower()
        bucket = 0 if name.startswith("normal") else 1 if name.startswith("pneumonia") else 2
        return (bucket, str(p))

    ordered = sorted(imgs, key=rank)
    return ordered[:n] if n else ordered


def load_manifest() -> Optional[dict]:
    """Load the preprocessed manifest, or None if not generated yet."""
    if not MANIFEST_PATH.exists():
        return None
    import json
    return json.loads(MANIFEST_PATH.read_text())


def _all_figures() -> list[Path]:
    """Return all valid image paths, preferring the manifest for speed."""
    # Fast path: use the preprocessed manifest if available
    manifest = load_manifest()
    if manifest and manifest.get("images"):
        paths = [Path(img["path"]) for img in manifest["images"]
                 if Path(img["path"]).exists()]
        if paths:
            return sorted(paths)

    # Slow fallback: rglob scan
    if not CHESTAGENTBENCH_DIR.exists():
        return []
    return sorted(
        p for p in CHESTAGENTBENCH_DIR.rglob("*")
        if p.suffix.lower() in _IMAGE_EXTS
        and "thumbnails" not in str(p)  # exclude generated thumbnails
    )


def sample(n: int = 1, pathology: str | None = None, modality: str = "cxr",
           seed: int | None = 0) -> list[Path]:
    """Return ``n`` sample image paths from the ChestAgentBench figures.

    Args:
        n: number of images to return.
        pathology: not yet supported (figures lack per-image pathology labels);
            passing it logs no error but currently does not filter. Phase 3+ may
            wire this through the benchmark metadata. Reserved for forward-compat.
        modality: reserved; only "cxr" is available in v1.
        seed: deterministic selection by default; pass ``None`` for random.

    Raises:
        FileNotFoundError: if the figures bundle has not been downloaded yet.
    """
    figures = _all_figures()
    if not figures:
        raise FileNotFoundError(
            f"No ChestAgentBench figures found under {CHESTAGENTBENCH_DIR}. "
            "Run `python scripts/setup.py` first."
        )
    if n >= len(figures):
        return figures
    if seed is None:
        return random.sample(figures, n)
    return random.Random(seed).sample(figures, n)
